In [6]:
import numpy as np
from mth433 import row_reduce as rr

def _find_pivots(R, tol=1e-12):
    """Pivot column indices from an RREF matrix R."""
    pivots = []
    for i in range(R.shape[0]):
        row = R[i]
        nz = np.where(np.abs(row) > tol)[0]
        if nz.size:
            pivots.append(nz[0])
    return pivots

def basis_col_pivot(A, tol=1e-12):
    """
    Basis for Col(A) using *pivot columns of the original A* (class style).
    Returns (basis_columns_as_2D_array, pivot_indices_list).
    """
    R = rr(A.astype(float).copy())
    piv = _find_pivots(R, tol)
    B = np.column_stack([A[:, j] for j in piv]) if piv else np.zeros((A.shape[0], 0))
    return B, piv

def basis_null_rref(A, tol=1e-12):
    """
    Basis for Null(A) using RREF (one vector per free column).
    Returns a 2D array with basis vectors as columns.
    """
    R = rr(A.astype(float).copy())
    m, n = R.shape
    piv = _find_pivots(R, tol)
    free = [j for j in range(n) if j not in piv]
    if not free:
        return np.zeros((n, 0))
    # Build one vector per free var f
    vecs = []
    for f in free:
        v = np.zeros(n)
        v[f] = 1.0
        # For each pivot row i with pivot col p, set x_p = -R[i,f]
        for i, p in enumerate(piv):
            coeff = R[i, f]
            if abs(coeff) > tol:
                v[p] = -coeff
        vecs.append(v)
    return np.column_stack(vecs)

In [7]:
A1 = np.array([[1,-3],
              [2,-6]], float)

# Class-style bases (match hand work)
Bcol, piv = basis_col_pivot(A1)
Bnull = basis_null_rref(A1)

print("Pivot columns:", piv)              # -> [0, 1]
print("Basis for Col(A1):\n", Bcol)        # columns are the pivot columns of ORIGINAL A
print("Basis for Null(A1):\n", Bnull)      # columns are the null-space basis vectors

Pivot columns: [0]
Basis for Col(A1):
 [[1.]
 [2.]]
Basis for Null(A1):
 [[3.]
 [1.]]


In [8]:
A2 = np.array([[0,0,-8],
              [1,2,-1],
              [2,4,6]], float)

# Class-style bases (match hand work)
Bcol, piv = basis_col_pivot(A2)
Bnull = basis_null_rref(A2)

print("Pivot columns:", piv)              # -> [0, 1]
print("Basis for Col(A2):\n", Bcol)        # columns are the pivot columns of ORIGINAL A
print("Basis for Null(A2):\n", Bnull)      # columns are the null-space basis vectors

Pivot columns: [0, 2]
Basis for Col(A2):
 [[ 0. -8.]
 [ 1. -1.]
 [ 2.  6.]]
Basis for Null(A2):
 [[-2.]
 [ 1.]
 [ 0.]]


In [9]:
A3 = np.array([[1,1,2,1],
              [1,0,-1,3],
              [2,3,7,0]], float)

# Class-style bases (match hand work)
Bcol, piv = basis_col_pivot(A3)
Bnull = basis_null_rref(A3)

print("Pivot columns:", piv)              # -> [0, 1]
print("Basis for Col(A2):\n", Bcol)        # columns are the pivot columns of ORIGINAL A
print("Basis for Null(A2):\n", Bnull)      # columns are the null-space basis vectors

Pivot columns: [0, 1]
Basis for Col(A2):
 [[1. 1.]
 [1. 0.]
 [2. 3.]]
Basis for Null(A2):
 [[-2. -1.]
 [ 3. -2.]
 [ 1.  0.]
 [ 0.  1.]]
