# Joe White - 08/27/2025

In [1]:
import numpy as np

In [2]:
A = np.random.rand(4,5)
print(A)

[[0.05088006 0.37998928 0.95163541 0.37923522 0.90001866]
 [0.58084841 0.41524571 0.86249792 0.74583953 0.98161092]
 [0.93041672 0.75012244 0.82377483 0.41797184 0.20587266]
 [0.50258761 0.590261   0.0502546  0.66512394 0.32397548]]


In [3]:
B = A[0:2,2:6]
print(B)

[[0.95163541 0.37923522 0.90001866]
 [0.86249792 0.74583953 0.98161092]]


In [10]:
array = np.array(range(14))
print(array)
C = np.reshape(array,(2,7))
print(C)
CT = C.T
print(CT)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[ 0  7]
 [ 1  8]
 [ 2  9]
 [ 3 10]
 [ 4 11]
 [ 5 12]
 [ 6 13]]
