# Joe White - 08/27/2025

In [1]:
import numpy as np

In [2]:
A = np.random.rand(4,5)
print(A)

[[0.72516157 0.56374838 0.45340838 0.99054926 0.08928937]
 [0.99046304 0.15355113 0.14101611 0.26308305 0.91574247]
 [0.27001292 0.04927597 0.14091724 0.38193798 0.43444507]
 [0.97396463 0.68455709 0.07995577 0.79154061 0.50817398]]


In [3]:
B = A[:2, -3:]
print(B)

[[0.45340838 0.99054926 0.08928937]
 [0.14101611 0.26308305 0.91574247]]


In [4]:
array = np.array(range(14))
C = array.reshape(2, 7)

CCt = C @ C.T
CtC = C.T @ C

print("Matrix C:")
print(C, "\n")

print("C*C^T:")
print(CCt, "\n")

print("C^T*C:")
print(CtC)

Matrix C:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]] 

C*C^T:
[[ 91 238]
 [238 728]] 

C^T*C:
[[ 49  56  63  70  77  84  91]
 [ 56  65  74  83  92 101 110]
 [ 63  74  85  96 107 118 129]
 [ 70  83  96 109 122 135 148]
 [ 77  92 107 122 137 152 167]
 [ 84 101 118 135 152 169 186]
 [ 91 110 129 148 167 186 205]]


In [5]:
print("The Shape of C^T*C is:", CtC.shape)

The Shape of C^T*C is: (7, 7)
