## Execute all of these cells and understand what is happening. I only use commands from the MatrixBasics Notebook. Do the 6 exercises at the end of the Notebook and turn it in.  

In [1]:
import numpy as np

In [2]:
A = np.array(range(-7,5)).reshape((6,2))

In [3]:
A

array([[-7, -6],
       [-5, -4],
       [-3, -2],
       [-1,  0],
       [ 1,  2],
       [ 3,  4]])

In [4]:
A.shape

(6, 2)

In [5]:
B = A[0:2]

In [6]:
B

array([[-7, -6],
       [-5, -4]])

In [7]:
B.shape

(2, 2)

In [8]:
C = A[:,0]
D = A[:,0:1]
E = A[:,-1]
F = A[:,1:]
for matrix in [C,D,E,F]:
    print(matrix)

[-7 -5 -3 -1  1  3]
[[-7]
 [-5]
 [-3]
 [-1]
 [ 1]
 [ 3]]
[-6 -4 -2  0  2  4]
[[-6]
 [-4]
 [-2]
 [ 0]
 [ 2]
 [ 4]]


## One might expect that C and D would be the same (but they aren't, see above).  Check out their shapes 

In [9]:
C.shape

(6,)

In [10]:
D.shape

(6, 1)

In [11]:
E.shape

(6,)

In [12]:
F.shape

(6, 1)

## Sometimes it doesn't matter if you use C or D but sometimes it does.  For example:

In [13]:
G = np.vstack((C,E))
H = np.vstack((D,F))

In [14]:
G

array([[-7, -5, -3, -1,  1,  3],
       [-6, -4, -2,  0,  2,  4]])

In [15]:
H

array([[-7],
       [-5],
       [-3],
       [-1],
       [ 1],
       [ 3],
       [-6],
       [-4],
       [-2],
       [ 0],
       [ 2],
       [ 4]])

In [16]:
G.shape

(2, 6)

In [17]:
H.shape

(12, 1)

## Perform the following operations using indexing, matrix operations and vstack/hstack.  Do not make any matrices "by hand" 

In [18]:
X = np.array(range(-6,6)).reshape((6,2))
Y = np.array(range(3,15)).reshape((6,2))

print(f"{X}\n")
print(f"{Y}\n")

[[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 0  1]
 [ 2  3]
 [ 4  5]]

[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]



This is what I'm looking for on these problems:

Sample Problem: Multiply the last column of X by the traspose of the first column of Y

Sample Answer:

In [19]:
X[:,1:] @ Y[:,0:1].T

array([[-15, -25, -35, -45, -55, -65],
       [ -9, -15, -21, -27, -33, -39],
       [ -3,  -5,  -7,  -9, -11, -13],
       [  3,   5,   7,   9,  11,  13],
       [  9,  15,  21,  27,  33,  39],
       [ 15,  25,  35,  45,  55,  65]])

1. Add the first 5 rows of X to the last 5 rows of X (so the result should have shape (5,2))
2. Add the second column of X to the first column of X (so the result should have shape (6,1))
3. Stack the first column of X on top of the second column of Y (so the result should have shape (12,1))
4. Stack the first column of Y to the left of the first column of X (so the result should have shape (6,2))
5. Add the first 4 rows of Y, the middle four rows of Y and the last 4 rows of Y together (so the result should have shape (4,2))
6. Subtract 3 times the middle 4 rows of Y from 1/2 the last 4 rows of X
7. Stack the first 4 rows of X on top of the last 4 rows of Y

In [20]:
# Question 1
print("----- Question 1 -----")
Q1 = X[0:5, :] + X[1:6, :]
print(f"{Q1}\n")
print(f"{Q1.shape}\n")

# Question 2
print("----- Question 2 -----")
Q2 = X[:, 0:1] + X[:, 1:2]
print(f"{Q2}\n")
print(f"{Q2.shape}\n")

# Question 3
print("----- Question 3 -----")
a = X[:,0:1]
b = Y[:,1:]
Q3 = np.vstack((a,b))
print(f"{Q3}\n")
print(f"{Q3.shape}\n")

# Question 4
print("----- Question 4 -----")
c = Y[:,0:1]
d = X[:,0:1]
Q4 = np.hstack((c,d))
print(f"{Q4}\n")
print(f"{Q4.shape}\n")

# Question 5
print("----- Question 5 -----")
Q5 = Y[0:4, :] + Y[1:5, :] + Y[2:6, :]
print(f"{Q5}\n")
print(f"{Q5.shape}\n")

# Question 6
print("----- Question 6 -----")
Q6 = (1/2)*X[2:6,:] - 3*Y[1:5, :]
print(f"{Q6}\n")
print(f"{Q6.shape}\n")

# Question 7
print("----- Question 7 -----")
e = X[0:4,:]
f = Y[2:6, :]
Q7 = np.vstack((e,f))
print(f"{Q7}\n")
print(f"{Q7.shape}\n")

----- Question 1 -----
[[-10  -8]
 [ -6  -4]
 [ -2   0]
 [  2   4]
 [  6   8]]

(5, 2)

----- Question 2 -----
[[-11]
 [ -7]
 [ -3]
 [  1]
 [  5]
 [  9]]

(6, 1)

----- Question 3 -----
[[-6]
 [-4]
 [-2]
 [ 0]
 [ 2]
 [ 4]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]]

(12, 1)

----- Question 4 -----
[[ 3 -6]
 [ 5 -4]
 [ 7 -2]
 [ 9  0]
 [11  2]
 [13  4]]

(6, 2)

----- Question 5 -----
[[15 18]
 [21 24]
 [27 30]
 [33 36]]

(4, 2)

----- Question 6 -----
[[-16.  -18.5]
 [-21.  -23.5]
 [-26.  -28.5]
 [-31.  -33.5]]

(4, 2)

----- Question 7 -----
[[-6 -5]
 [-4 -3]
 [-2 -1]
 [ 0  1]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]

(8, 2)

