### Three Extremely Useful shortcuts

When a cell is highlighted (there is a blue rectangle around the entire cell) you can press the 'x' key to delete the cell, press the 'a' key to insert a blank cell above it or press the 'b' key to insert a cell below it.  Try it now--insert a cell above and then delete it. Alternatively there are also buttons in each cell that you can click on with you mouse/pad to acheive the same thing. 

### Kernel restarts are also extrememly useful
1. After you have executed a couple cells click on the Kernel button above and select 'Restart Kernel and Clear Outputs of all Cells'
2. After you have worked through the Notebook click on the Kernel button above and select 'Restart Kernel and Run all Cells'

# Matrix Basics

In [2]:
import numpy as np

### The [numpy documentaion](https://numpy.org/doc/2.1/) is the place to learn more about numpy.  My tutorials will always contain direct links to the relevant part of the documenation.

## A. Very useful matrices

### 1. How to make a matrix by "hand"

Arrays will be the most common data structure used in this course.
[np.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) is the command we use to build a matrix 'by hand'.  
For example to define the matrix

$\left[\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6  \end{array}\right]$

use the command

In [2]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

# Remark: First I defined the matrix A.  Then I typed A.  This tells Jupyter to display A.  Notice what happens in the next cell.  The matrix A is defined but Jupyter does not display it.

In [3]:
A = np.array([[5,4,3,2],[1,2,1,1]])

To display it type 'A' into a Code cell:

In [4]:
A

array([[5, 4, 3, 2],
       [1, 2, 1, 1]])

Furthermore if I hadn't used a variable at all, the matrix would be automatically displayed

In [5]:
np.array([[6.5,5],[75,-1]])

array([[ 6.5,  5. ],
       [75. , -1. ]])

### 2. How to make a zero matrix

The command [np.zeros((m,n))](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)
constructs the $m\times n$ zero matrix. 

For example to define the matrix

$\left[\begin{array}{cc} 0 & 0\\ 0 & 0\\ 0 & 0  \end{array}\right]$

use the command

In [6]:
A = np.zeros((3,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

What do you think np.ones does? Insert a new cell below this one and try it out

In [4]:
A = np.ones((2,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 3. How to make an identity matrix

The command [np.eye(n)](https://numpy.org/devdocs/reference/generated/numpy.eye.html) constructs an $n\times n$ identity matrix.

For example to define the matrix

$\left[ \begin{array}{cccc} 1 & 0 & 0 & 0\\ 0 & 1 & 0 & 0\\ 0 & 0 & 1 & 0\\ 0 & 0 & 0 & 1   \end{array} \right]$

use the command

In [7]:
A = np.eye(4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 4. Three ways to make test matrices

We need methods to painlessly generate matrices that we can test in our functions.

The command [np.random.rand(m,n)](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)
generates a mxn matrix with entries chosen uniformly from (0,1).

For example to define a random 3x2 matrix use the command

In [8]:
A = np.random.rand(3,2)
A

array([[0.29640881, 0.55992877],
       [0.72665355, 0.44418567],
       [0.26525806, 0.78704771]])

The command [np.random.randint(a,b,(m,n))](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) generates a random $m\times n$ matrix with integer entries in the range $[a,b).$

For example to make a $4\times 3$ matrix with entries between $-6$ and $10$ use the command

In [9]:
A = np.random.randint(-6,10,(4,3))
A

array([[ 1,  5, -4],
       [ 0, -1,  6],
       [ 0,  4,  4],
       [-1, -6,  3]])

Here's another convenient way to generate test matrices.  Suppose I want a $5\times 5$ matrix with entries 0 to 24 but don't want to type 25 different entries.  We can use Python's [range](https://docs.python.org/3/library/functions.html#func-range) function and Numpy's [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to acheive this in a couple lines:

In [10]:
A = np.array(range(25))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Now we reshape this $1\times 25$ matrix into a $5\times 5$ matrix:

In [11]:
B = np.reshape(A,(5,5))
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## B. Manipulating matrices

### 1. Constructing Submatrices

Numpy calls these operations [indexing](https://numpy.org/doc/stable/user/basics.indexing.html)

Start with a random 4x5 matrix A

In [12]:
A = np.random.rand(4,5)
A

array([[0.73308537, 0.69285608, 0.95728558, 0.55092154, 0.71126716],
       [0.8438296 , 0.72384637, 0.93768575, 0.96182917, 0.4160222 ],
       [0.22272195, 0.15204206, 0.13239444, 0.17239427, 0.43695471],
       [0.6665389 , 0.90080198, 0.90950424, 0.25057783, 0.35783527]])

Obtain a submatrix consisting of rows a to b and columns c to d
<br> with the command A[a:b+1, c:d+1]. 
<br> For example to define the 3x2 submatrix of A consisting of 
<br> rows 1 to 3 and columns 0 to 1 use the command

In [13]:
B = A[1:4,0:2]
B

array([[0.8438296 , 0.72384637],
       [0.22272195, 0.15204206],
       [0.6665389 , 0.90080198]])

We commonly want to define a submatrix that has ALL rows 
<br>and only some of the columns (or vice versa).
<br>A useful shortcut:  A[:,a:b+1] is the submatrix consisting
<br>of all rows, but only columns a to b while A[a:b+1,:] gives the submatrix 
<br>consisting or all columns, but only rows a to b.
<br>For example to define the submatrix of A consisting of all rows, but only columns 1 to 3 use the command

In [14]:
C = A[:,1:4]
C

array([[0.69285608, 0.95728558, 0.55092154],
       [0.72384637, 0.93768575, 0.96182917],
       [0.15204206, 0.13239444, 0.17239427],
       [0.90080198, 0.90950424, 0.25057783]])

And to define the submatrix that is all columns and the first 2 rows use

In [15]:
D = A[0:2,:]
D

array([[0.73308537, 0.69285608, 0.95728558, 0.55092154, 0.71126716],
       [0.8438296 , 0.72384637, 0.93768575, 0.96182917, 0.4160222 ]])

This is helpful as well.  Do you see what it does?

In [16]:
E = A[0:3,2:]
E

array([[0.95728558, 0.55092154, 0.71126716],
       [0.93768575, 0.96182917, 0.4160222 ],
       [0.13239444, 0.17239427, 0.43695471]])

### 2. Concatenating matrices
<br> 
<br> Sometimes we need to "glue" matrices together. For example define

$X_1 = \left[  \begin{array}{rrr}1.2 & -3 & 0\\ 10.1 & 6.23 & -0.22 \end{array}  \right],\quad X_2 = \left[\begin{array}{rr}   1 & 0\\ 2 & -3 \end{array}\right], \quad X_3 = \left[\begin{array}{ccc} 5 & -6 & 3.441 \end{array}  \right]$

We want to easily construct the matrices
$\left[ \begin{array}{cc} X_1 & X_2  \end{array}  \right] = \left[ \begin{array}{rrrrr} 1.2 & -3 & 0 & 1 & 0\\ 10.1 & 6.23 & -0.22 & 2 & -3  \end{array}  \right]$ and $\left[\begin{array}{c} X_1\\ X_3  \end{array}  \right] = \left[  \begin{array}{rrr}1.2 & -3 & 0\\ 10.1 & 6.23 & -0.22\\  5 & -6 & 3.441  \end{array}  \right]$

The relevant respective commands are [hstack (h for horizontal)](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html#numpy.hstack) and [vstack (v for vertical)](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html).  For example:

In [17]:
A = np.random.rand(2,2)
B = np.random.rand(2,2)
C = np.vstack((A,B))
D = np.hstack((A,B))
print('A is the matrix:\n')
print(A)
print('\n B is the matrix:\n')
print(B)
print('\n Stack A on top of B to obtain\n')
print(C)
print('\n Stack B to the right of A to obtain\n')
print(D)

A is the matrix:

[[0.48759186 0.75560921]
 [0.16267164 0.31498831]]

 B is the matrix:

[[0.47091513 0.08634215]
 [0.43672771 0.26180614]]

 Stack A on top of B to obtain

[[0.48759186 0.75560921]
 [0.16267164 0.31498831]
 [0.47091513 0.08634215]
 [0.43672771 0.26180614]]

 Stack B to the right of A to obtain

[[0.48759186 0.75560921 0.47091513 0.08634215]
 [0.16267164 0.31498831 0.43672771 0.26180614]]


### 3. Changing entries to a matrix
Start with a random matrix

In [18]:
A = np.random.rand(3,4)
A

array([[0.22276377, 0.37058174, 0.04064376, 0.97882247],
       [0.51413145, 0.00104549, 0.33770862, 0.38013718],
       [0.71299786, 0.23952443, 0.10534681, 0.70863693]])

Change a single entry as follows

In [19]:
A[0,2] = 6
A

array([[2.22763768e-01, 3.70581744e-01, 6.00000000e+00, 9.78822472e-01],
       [5.14131451e-01, 1.04548810e-03, 3.37708618e-01, 3.80137184e-01],
       [7.12997862e-01, 2.39524428e-01, 1.05346807e-01, 7.08636931e-01]])

We can also change entire submatrices.  For example, make the entire last column of A all zeros

In [20]:
A[:,3:4] = np.zeros((3,1))
A

array([[2.22763768e-01, 3.70581744e-01, 6.00000000e+00, 0.00000000e+00],
       [5.14131451e-01, 1.04548810e-03, 3.37708618e-01, 0.00000000e+00],
       [7.12997862e-01, 2.39524428e-01, 1.05346807e-01, 0.00000000e+00]])

Or redefine a submatrix of A as anything you need

In [21]:
B = np.array([[-3,4],[9.008, 15]])
A[1:3,0:2] = B
A

array([[ 0.22276377,  0.37058174,  6.        ,  0.        ],
       [-3.        ,  4.        ,  0.33770862,  0.        ],
       [ 9.008     , 15.        ,  0.10534681,  0.        ]])

## C. The most common matrix functions

Start with the matrix $A = \left[  \begin{array}{rrr} 4 & 6 & -2\\ -1/2 & 3 & -12  \end{array} \right]$

### 1. shape: 
Use the [shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape) command to get the number of rows and columns of a matrix.  In particular
m,n = A.shape will give the size of the matrix

In [22]:
A = np.array([[4,6,-2],[-1/2, 3, -12]])
m,n = A.shape
print(m)
print(n)
print(A.shape)

2
3
(2, 3)


### 2. Transpose

[A.T](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html#numpy.ndarray.T) gives the transpose of A. Notice the size of the transpose

In [23]:
B = A.T
print(B)
print(B.shape)

[[  4.   -0.5]
 [  6.    3. ]
 [ -2.  -12. ]]
(3, 2)


### 3. Multiplication
The @ symbol is the most convenient way to perform matrix multiplication

In [24]:
C = A @ B
D = B @ A
print(C)
print('\n')
print(D)
print('\n')
print(f"The size of A@B is {C.shape} and the size of B@A is {D.shape}")

[[ 56.    40.  ]
 [ 40.   153.25]]


[[ 16.25  22.5   -2.  ]
 [ 22.5   45.   -48.  ]
 [ -2.   -48.   148.  ]]


The size of A@B is (2, 2) and the size of B@A is (3, 3)


### 4. Addition and scalar multiplication
They are + and * respecitively

In [25]:
print(np.eye(4))
print('\n')
print(np.ones((4,4)))
print('Add them together to obtain')
print('\n')
print(np.eye(4) + np.ones((4,4)))
print('Scalar multiply the identity by 5 to obtain')
print('\n')
print(5*np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Add them together to obtain


[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]
Scalar multiply the identity by 5 to obtain


[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


We also use '*' as an operation on matrices.  Do you see what it does?

In [26]:
A = np.array(range(1,7)).reshape(2,3)
B = np.array(range(3,9)).reshape(2,3)
print('A is')
print(A)
print('and B is')
print(B)
print('So A*B is')
print(A*B)

A is
[[1 2 3]
 [4 5 6]]
and B is
[[3 4 5]
 [6 7 8]]
So A*B is
[[ 3  8 15]
 [24 35 48]]


### 5. [allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html#numpy-allclose)
Now for some computing realities. Due to round off error we will accept that matrices that are 'close' are equal.  We use np.allclose to acheive this. The term 'close' is relative but for our purposes the default value of close ($10^{-8}$) will suffice. np.allclose(A,B) returns True if the matrices A and B are elementwise within $10^{-8}$ of each other. Here are some examples

In [ ]:
A = np.random.rand(2,2)
B = np.random.rand(2,2)
print(A)
print(B)
np.allclose(A,B)

The command A == B gives a truth valued matrix.  The (i,j) entry of A == B is 'True' if A[i,j] = B[i,j] and 'False' otherwise. That is too rigid for most purposes.  For example

In [ ]:
A = np.zeros((2,2))
B = np.array([[0.0000000001,0],[0.0000000001,0.00000000001]])
print(A)
print(B)
print(A == B)

But np.allclose is more flexible and useful for computational linear algebra

In [ ]:
np.allclose(A,B)